# Productionisation (Model Deserialization)

In [1]:
import numpy as np
from pickle import load

In [2]:
# Loading pretrained classifiers from pickle file

scaler = load(open('standard_scaler.pkl', 'rb'))
knn_classifier = load(open('knn_model.pkl', 'rb'))
lr_classifier = load(open('lr_model.pkl', 'rb'))
nb_classifier = load(open('nb_model.pkl', 'rb'))
dt_classifier = load(open('dt_model.pkl', 'rb'))
sv_classifier = load(open('sv_model.pkl', 'rb'))

In [3]:
Preg = int(input('Enter Pregnancies :'))
Glucose= int(input('Enter Glucose :'))
BP= int(input('Enter Blood Pressure :'))

ST= int(input('Enter Skin Thickness :'))

Insulin = int(input('Enter Insulin :'))
BMI= float(input('Enter BMI :'))
DPF=float(input('Enter Diabetes Pedigree Function :'))
Age= int(input('Enter Age :'))

Enter Pregnancies :8
Enter Glucose :183
Enter Blood Pressure :64
Enter Skin Thickness :0
Enter Insulin :0
Enter BMI :23.3
Enter Diabetes Pedigree Function :0.672
Enter Age :32


In [4]:
scaler.transform([Preg, Glucose, BP,ST, Insulin, BMI, DPF, Age])

ValueError: Expected 2D array, got 1D array instead:
array=[  8.    183.     64.      0.      0.     23.3     0.672  32.   ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
knn_classifier.predict([Preg, Glucose, BP,ST, Insulin, BMI, DPF, Age])

ValueError: Expected 2D array, got 1D array instead:
array=[  8.    183.     64.      0.      0.     23.3     0.672  32.   ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [6]:
query_point = np.array([Preg, Glucose, BP,ST, Insulin, BMI, DPF, Age])

In [7]:
query_point

array([  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
        32.   ])

In [8]:
query_point.reshape(1, -1)

array([[  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ]])

In [9]:
query_point = query_point.reshape(1, -1)

query_point

array([[  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ]])

In [10]:
query_point_transformed = scaler.transform(query_point)

query_point_transformed

array([[ 1.23355973,  1.93723887, -0.28145571, -1.29075209, -0.70188945,
        -1.10978932,  0.60136622, -0.10709711]])

In [12]:
prediction=knn_classifier.predict(query_point_transformed)
if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

The person is diabetic
